:art: improve pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,4 +1,6 @@
 #!/bin/bash
+# ----------------------------------------------------------------------------------------------------------------------
+echo "[ + ] Step 1 check branch name."
 
 # Get the branch being pushed
 current_branch=$(git symbolic-ref --short HEAD)
@@ -16,19 +18,13 @@ for pattern in "${allowed_patterns[@]}"; do
 done
 
 if [ "$matched" = false ]; then
-  echo "Error: Branch '$current_branch' is not allowed to commit. Allowed patterns are: ${allowed_patterns[*]}"
+  echo "Error: Branch '$current_branch' is not allowed to commit. Allowed patterns are: ${allowed_patterns[*]}."
   exit 1
 fi
 
-PHP_CONTAINER=$(docker compose ps -q laravel.test 2>/dev/null)
-
-run_cmd() {
-    if [ -n "$PHP_CONTAINER" ]; then
-        docker compose exec -T laravel.test "$@"
-    else
-        "$@"
-    fi
-}
+echo "[ + ] Step 1 passed ✓."
+# ----------------------------------------------------------------------------------------------------------------------
+echo "[ + ] Step 2 check author."
 
 # Define your whitelist of allowed author names and emails
 allowed_names=("Mohamadreza Rezaei")
@@ -49,7 +45,34 @@ if [[ ! " ${allowed_emails[@]} " =~ " ${author_email} " ]]; then
   echo "Error: Author email '${author_email}' is not allowed."
   exit 1
 fi
-echo "Pint"
+echo "[ + ] Step 2 passed ✓."
+# ----------------------------------------------------------------------------------------------------------------------
+# [ + ] methods
+
+PHP_CONTAINER=$(docker compose ps -q laravel.test 2>/dev/null)
+
+run_cmd() {
+    if [ -n "$PHP_CONTAINER" ]; then
+        docker compose exec -T laravel.test "$@"
+    else
+        "$@"
+    fi
+}
+
+# ----------------------------------------------------------------------------------------------------------------------
+echo "[ + ] Step 3 check rector."
+
+run_cmd vendor/bin/rector process --dry-run
+rector_exit_code=$?
+
+# If rector failed, exit
+if [ $rector_exit_code -ne 0 ]; then
+  exit 1
+fi
+echo "[ + ] Step 3 passed ✓."
+# ----------------------------------------------------------------------------------------------------------------------
+echo "[ + ] Step 4 check pint."
+
 # Run Pint and capture output
 pint_output=$(run_cmd vendor/bin/pint --parallel --dirty 2>&1)
 pint_exit_code=$?
@@ -75,23 +98,20 @@ if [ -n "$fixed_files" ]; then
   done <<< "$fixed_files"
   echo ""
 fi
-echo "Tests"
-run_cmd php artisan test
+echo "[ + ] Step 4 passed ✓."
+# ----------------------------------------------------------------------------------------------------------------------
+echo "[ + ] Step 5 check tests."
+
+run_cmd php artisan test --parallel --processes=8 --stop-on-failure
 test_exit_code=$?
 
 # If Test failed, exit
 if [ $test_exit_code -ne 0 ]; then
   exit 1
 fi
+echo "[ + ] Step 5 passed ✓."
+# ----------------------------------------------------------------------------------------------------------------------
+echo "[ + ] Finish ✓✓✓."
 
-echo "Rector"
-run_cmd vendor/bin/rector process --dry-run
-rector_exit_code=$?
-
-# If Test failed, exit
-if [ $rector_exit_code -ne 0 ]; then
-  exit 1
-fi
-
-# If both checks pass, allow the commit
+# If checks pass, allow the commit
 exit 0
